### ISSUE TITLE
CFNClusterManager does not overwrite preexisting config file

### ISSUE THREAD

**Issue by artnasamran** [ucsd-ccbb/cirrus-ngs#22]
In step 1.5.1 of "BasicCFNClusterSetup.jpynb", CFNClusterManager fails to overwrite the .cfncluser/config file on the local machine.

**Comment by artnasamran** [comment]
In the same notebook, step 1.5.3, the default cluster_template parameter, "cluster_template = elasticsearch", throws a KeyError. See below:

> Traceback (most recent call last):
>   File "/Users/artnasamran/anaconda3/lib/python3.6/configparser.py", line 1138, in _unify_values
>     sectiondict = self._sections[section]
> KeyError: 'cluster elasticsearch'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/Users/artnasamran/anaconda3/bin/cfncluster", line 11, in <module>
>     sys.exit(main())
>   File "/Users/artnasamran/anaconda3/lib/python3.6/site-packages/cfncluster/cli.py", line 161, in main
>     args.func(args)
>   File "/Users/artnasamran/anaconda3/lib/python3.6/site-packages/cfncluster/cli.py", line 35, in list
>     cfncluster.list(args)
>   File "/Users/artnasamran/anaconda3/lib/python3.6/site-packages/cfncluster/cfncluster.py", line 213, in list
>     config = cfnconfig.CfnClusterConfig(args)
>   File "/Users/artnasamran/anaconda3/lib/python3.6/site-packages/cfncluster/cfnconfig.py", line 136, in __init__
>     self.key_name = __config.get(self.__cluster_section, 'key_name')
>   File "/Users/artnasamran/anaconda3/lib/python3.6/configparser.py", line 781, in get
>     d = self._unify_values(section, vars)
>   File "/Users/artnasamran/anaconda3/lib/python3.6/configparser.py", line 1141, in _unify_values
>     raise NoSectionError(section)
> configparser.NoSectionError: No section: 'cluster elasticsearch'

KeyError is not raised if cluster_template is manually changed to "ccbb".
